import { dirname, relative } from "node:path";

import type { PluginManifest } from "@agentic-test-hub/plugin";

import { executorKindsFor, type GenerationPlan } from "./plan.ts";

/** Where a generated file will live, and what it needs to reach the manifest. */
export interface RenderTarget {
  /** Absolute path to the plugin manifest the generated file loads at run time. */
  readonly manifestPath: string;
  /** Absolute path the generated file will be written to. */
  readonly outPath: string;
}

const EXECUTOR_IMPORTS: Readonly<Record<string, string>> = {
  http: "HttpExecutor",
  shell: "ShellExecutor",
  browser: "BrowserExecutor",
};

/** A relative path suitable for a generated file's own `import.meta.url`-based lookup. */
function importPathFor(target: RenderTarget): string {
  const rel = relative(dirname(target.outPath), target.manifestPath).split("\\").join("/");
  return rel.startsWith(".") ? rel : `./${rel}`;
}

function registrations(kinds: readonly string[]): string {
  const lines: string[] = [];
  if (kinds.includes("http")) lines.push("  registry.register(new HttpExecutor());");
  if (kinds.includes("shell")) lines.push("  registry.register(new ShellExecutor());");
  if (kinds.includes("browser")) {
    lines.push("  registry.register(new BrowserExecutor(new PlaywrightDriver()));");
  }
  return lines.join("\n");
}

/**
 * Renders a generated Playwright test (TypeScript) for `plan`.
 *
 * The generated file's own job is only to load the manifest, build a
 * registry with the executors the plan actually touches, and call
 * `runCase`/`runScenario` — every resolution/derivation decision (which
 * overrides are expressible, which operation runs, what evidence policy
 * applies) already happened in {@link plan.ts | planGeneration} and is
 * inlined below as plain data, so the generated file never re-parses YAML
 * or re-applies overrides.
 */
export function renderSpecFileTs(
  plan: GenerationPlan,
  manifest: PluginManifest,
  target: RenderTarget,
): string {
  const kinds = executorKindsFor(plan, manifest);
  const executorImports = kinds
    .map((kind) => EXECUTOR_IMPORTS[kind])
    .filter((name): name is string => name !== undefined);
  const runnerImports = [
    "ExecutorRegistry",
    ...executorImports,
    ...(kinds.includes("browser") ? ["PlaywrightDriver"] : []),
    plan.kind === "case" ? "runCase" : "runScenario",
  ];

  const manifestImportPath = importPathFor(target);
  const entity = plan.kind === "case" ? plan.testCase : plan.scenario;
  const title = plan.kind === "case" ? plan.testCase.summary : plan.scenario.title;

  const body =
    plan.kind === "case"
      ? `  const result = await runCase(testCase, baseline, registry, context);
  expect(result.verdict, JSON.stringify(result, null, 2)).toBe("pass");`
      : `  const result = await runScenario(scenario, registry, context);
  expect(result.verdict, JSON.stringify(result, null, 2)).toBe("pass");`;

  const dataDecl =
    plan.kind === "case"
      ? `const baseline = Baseline.parse(${JSON.stringify(plan.baseline, null, 2)});
const testCase = TestCase.parse(${JSON.stringify(entity, null, 2)});`
      : `const scenario = Scenario.parse(${JSON.stringify(entity, null, 2)});`;

  const coreImports = plan.kind === "case" ? ["Baseline", "TestCase"] : ["Scenario"];

  return `/**
 * Generated by ath-generate-test from ${plan.id}. Do not hand-edit the
 * inlined data below; regenerate with --force instead. Assertions and setup
 * around the generated call are yours to extend.
 */
import { readFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { expect, test } from "@playwright/test";

import { ${coreImports.join(", ")} } from "@agentic-test-hub/core";
import { loadManifest } from "@agentic-test-hub/plugin";
import type { ExecutionContext } from "@agentic-test-hub/runner";
import { ${runnerImports.join(", ")} } from "@agentic-test-hub/runner";

const manifestPath = fileURLToPath(new URL(${JSON.stringify(manifestImportPath)}, import.meta.url));
const manifest = loadManifest(readFileSync(manifestPath, "utf8")).manifest;

${dataDecl}

test(${JSON.stringify(`${plan.id}: ${title}`)}, async () => {
  const registry = new ExecutorRegistry();
${registrations(kinds)}
  const context: ExecutionContext = { manifest, scopes: {}, root: dirname(manifestPath) };
${body}
});
`;
}
