"""
Browser evidence: sessions closed exactly once (fake driver), then real
Chromium on a page served locally, through a test generated by the real CLI.
"""

from __future__ import annotations

import json
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import pytest
from live_plugin import BASELINE, PLUGIN, make_case
from live_support import (
    generate,
    live_server,
    load_index,
    requires_browser,
    run_generated,
    write_specs,
    write_yaml,
)

from agentic_test_hub_runner import (
    BrowserExecutor,
    ExecutionContext,
    ExecutorError,
    ExecutorRegistry,
    Manifest,
    run_scenario,
)


class FakeSession:
    def __init__(self) -> None:
        self.closed = 0

    def goto(self, url: str) -> None: ...
    def fill(self, selector: str, value: str) -> None: ...
    def click(self, selector: str) -> None: ...
    def select(self, selector: str, value: str) -> None: ...
    def upload(self, selector: str, file: str) -> None: ...
    def wait_for(self, selector: str, timeout_ms: int) -> None: ...
    def text_of(self, selector: str) -> str | None:
        return "page"

    def screenshot(self) -> bytes:
        return b"png"

    def current_url(self) -> str:
        return "about:blank"

    def console_messages(self) -> list[Any]:
        return []

    def network_exchanges(self) -> list[Any]:
        return []

    def close(self) -> None:
        self.closed += 1


class FakeDriver:
    def __init__(self) -> None:
        self.sessions: list[FakeSession] = []

    def open(self, base_url: str) -> FakeSession:
        self.sessions.append(FakeSession())
        return self.sessions[-1]


MANIFEST = Manifest(
    name="fake",
    connections={"ui": {"kind": "browser", "baseUrl": "http://x.invalid"}},
    operations={
        "OP-OPEN": {
            "executor": "browser",
            "connection": "ui",
            "steps": [{"action": "goto", "url": "http://x.invalid/"}],
        }
    },
    states={},
    evidence={},
    policy=None,
    extension_module=None,
)


def _scenario(*operations: str) -> dict[str, Any]:
    return {
        "id": "SC-FAKE",
        "steps": [
            {
                "id": f"S-{index}",
                "action": {"operation": operation, "params": {}},
                "expect": [],
                "polarity": "nominal",
            }
            for index, operation in enumerate(operations)
        ],
        "evidence": {"sources": [], "timing": "after"},
    }


def test_each_session_is_closed_exactly_once_and_only_the_last_stays_open_meanwhile() -> None:
    driver = FakeDriver()
    executor = BrowserExecutor(driver)
    registry = ExecutorRegistry().register(executor)
    context = ExecutionContext(manifest=MANIFEST, scopes={})
    registry.run("OP-OPEN", {}, context)
    registry.run("OP-OPEN", {}, context)
    first, second = driver.sessions
    assert (first.closed, second.closed) == (1, 0)
    assert registry.browser_session() is second
    registry.close_all()
    registry.close_all()
    assert (first.closed, second.closed) == (1, 1)
    assert registry.browser_session() is None


def test_run_scenario_closes_the_session_even_when_a_step_raises() -> None:
    driver = FakeDriver()
    registry = ExecutorRegistry().register(BrowserExecutor(driver))
    context = ExecutionContext(manifest=MANIFEST, scopes={})
    with pytest.raises(ExecutorError):
        run_scenario(_scenario("OP-OPEN", "OP-UNDECLARED"), registry, context)
    assert [session.closed for session in driver.sessions] == [1]


def test_a_supplied_session_is_never_closed_by_the_executor() -> None:
    session = FakeSession()
    executor = BrowserExecutor(FakeDriver(), session)
    registry = ExecutorRegistry().register(executor)
    registry.run("OP-OPEN", {}, ExecutionContext(manifest=MANIFEST, scopes={}))
    registry.close_all()
    assert session.closed == 0 and registry.browser_session() is session


def _generate_case(tmp_path: Path, plugin: dict[str, Any], case: dict[str, Any]) -> Path:
    plugin_path = tmp_path / "plugin.yaml"
    write_yaml(plugin_path, plugin)
    baseline = {
        **BASELINE,
        "action": {"operation": "OP-COMPOSE", "params": {}},
        "context": {"recipient": "browser@example.invalid"},
    }
    specs = write_specs(tmp_path, baseline, [case], [])
    return generate(tmp_path, specs, plugin_path, "TC-LIVE-001")


@requires_browser
def test_browser_case_saves_screenshots_console_and_network(tmp_path: Path) -> None:
    case = make_case(
        expect=[{"kind": "stdout_contains", "value": "status 201", "viewpoints": []}],
        evidence={"sources": ["app_log"], "timing": "after"},
    )
    test_file = _generate_case(tmp_path, PLUGIN, case)
    evidence_root = tmp_path / "evidence"
    with live_server() as (url, state):
        done = run_generated(
            test_file,
            {"APP_URL": url, "LIVE_TOKEN": "tok", "ATH_EVIDENCE_DIR": str(evidence_root)},
        )
    assert done.returncode == 0, done.stdout + done.stderr
    assert len(state.notifications) == 1

    run_dir, index = load_index(evidence_root)
    case_dir = run_dir / "TC-LIVE-001" / "case"
    assert (case_dir / "before-screenshot-OP-COMPOSE.png").read_bytes().startswith(b"\x89PNG")
    assert (case_dir / "after-screenshot-OP-COMPOSE.png").read_bytes().startswith(b"\x89PNG")

    console = json.loads((case_dir / "after-console-OP-COMPOSE.json").read_text())
    assert any(m["text"] == "boom from page" and m["level"] == "error" for m in console)

    network = json.loads((case_dir / "after-network-OP-COMPOSE.json").read_text())
    post = next(entry for entry in network if entry["method"] == "POST")
    assert post["status"] == 201
    assert json.loads(post["response_body_preview"])["notification"]["id"] == 1
    get = next(entry for entry in network if entry["method"] == "GET")
    assert get["response_body_preview"] is None

    kinds = {(entry["kind"], entry["source"]) for entry in index["entries"]}
    assert {(1, "screenshot"), (2, "browser_console"), (2, "browser_network")} <= kinds
    assert not index["warnings"]


@requires_browser
def test_console_errors_now_reach_the_verdict(tmp_path: Path) -> None:
    # Before the runner picked the browser session up by itself, a policy
    # binding browser_console never saw the page's console.error.
    strict = json.loads(json.dumps(PLUGIN))
    strict["policy"]["rules"]["nominal"]["browser_console"] = "clean"
    case = make_case(
        expect=[{"kind": "stdout_contains", "value": "status 201", "viewpoints": []}],
        evidence={"sources": ["app_log"], "timing": "after"},
    )
    test_file = _generate_case(tmp_path, strict, case)
    with live_server() as (url, _state):
        done = run_generated(test_file, {"APP_URL": url, "LIVE_TOKEN": "tok"}, verbose=True)
    assert done.returncode != 0
    assert "boom from page" in done.stdout


@requires_browser
def test_scenario_saves_each_browser_step_under_its_own_directory(tmp_path: Path) -> None:
    plugin_path = tmp_path / "plugin.yaml"
    write_yaml(plugin_path, PLUGIN)

    def step(
        step_id: str, operation: str, params: dict[str, Any], depends: list[str], text: str
    ) -> dict[str, Any]:
        return {
            "id": step_id,
            "summary": step_id,
            "action": {"operation": operation, "params": params},
            "expect": [{"kind": "stdout_contains", "value": text, "viewpoints": []}],
            "polarity": "nominal",
            "dependsOn": depends,
            "produces": {},
            "viewpoints": [],
        }

    scenario = {
        "id": "SC-LIVE-001",
        "title": "open, then compose",
        "preconditions": [],
        "steps": [
            step("S-OPEN", "OP-OPEN", {}, [], "live app"),
            step(
                "S-COMPOSE",
                "OP-COMPOSE",
                {"recipient": "x@example.invalid"},
                ["S-OPEN"],
                "status 201",
            ),
        ],
        "cleanup": [],
        "evidence": {"sources": ["app_log"], "timing": "after"},
        "evidenceWaivers": [],
        "tags": [],
        "viewpoints": [],
    }
    specs = write_specs(tmp_path, BASELINE, [], [scenario])
    test_file = generate(tmp_path, specs, plugin_path, "SC-LIVE-001")
    evidence_root = tmp_path / "evidence"
    with live_server() as (url, _state):
        done = run_generated(
            test_file,
            {"APP_URL": url, "LIVE_TOKEN": "tok", "ATH_EVIDENCE_DIR": str(evidence_root)},
        )
    assert done.returncode == 0, done.stdout + done.stderr
    run_dir, _index = load_index(evidence_root)
    base = run_dir / "SC-LIVE-001"
    assert (base / "01-S-OPEN" / "after-console-OP-OPEN.json").exists()
    assert (base / "02-S-COMPOSE" / "after-network-OP-COMPOSE.json").exists()
    assert (base / "02-S-COMPOSE" / "before-screenshot-OP-COMPOSE.png").exists()


class _SlowHandler(BaseHTTPRequestHandler):
    def log_message(self, format: str, *args: object) -> None:  # noqa: A002
        pass

    def _send(self, body: bytes, content_type: str) -> None:
        self.send_response(201 if self.command == "POST" else 200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:
        page = (
            "<button id=go onclick=\"fetch('/slow', {method: 'POST'})\">go</button>"
            "<script>console.log('ready')</script>"
        )
        self._send(page.encode(), "text/html")

    def do_POST(self) -> None:
        time.sleep(0.8)  # the response arrives well after the click returned
        self._send(b'{"ok": true}', "application/json")


@requires_browser
def test_logs_include_a_response_that_arrives_after_the_click_returned() -> None:
    from agentic_test_hub_runner.executors.browser import PlaywrightDriver

    server = ThreadingHTTPServer(("127.0.0.1", 0), _SlowHandler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    session = PlaywrightDriver().open(f"http://127.0.0.1:{server.server_address[1]}")
    try:
        session.goto("/")
        session.click("#go")
        # No wait for any page text: the log must still hold the POST, because
        # reading it waits for the request still in flight.
        post = [e for e in session.network_exchanges() if e.method == "POST"]
        assert [(e.status, e.response_body_preview) for e in post] == [(201, '{"ok": true}')]
    finally:
        session.close()
        server.shutdown()
        server.server_close()
