"""
Before/after collection (`timing: before_and_after`), end to end: tests
generated by the real CLI, run by pytest against a throwaway server.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from live_plugin import BASELINE, PLUGIN, make_case
from live_support import (
    generate,
    live_server,
    load_index,
    requires_cli,
    run_generated,
    write_specs,
    write_yaml,
)

SOURCES = ["app_log", "db_records", "db_log"]
NOISY_LOG = ["boot ok", "ERROR stale failure from last night"]


def _run_case(
    tmp_path: Path, timing: str, log: list[str] | None = None
) -> tuple[Any, Path, dict[str, Any]]:
    plugin = tmp_path / "plugin.yaml"
    write_yaml(plugin, PLUGIN)
    case = make_case(evidence={"sources": SOURCES, "timing": timing})
    specs = write_specs(tmp_path, BASELINE, [case], [])
    test_file = generate(tmp_path, specs, plugin, "TC-LIVE-001")
    evidence_root = tmp_path / "evidence"
    with live_server(log) as (url, _state):
        done = run_generated(
            test_file,
            {"APP_URL": url, "LIVE_TOKEN": "tok", "ATH_EVIDENCE_DIR": str(evidence_root)},
        )
    if not evidence_root.exists():
        return done, tmp_path, {}
    run_dir, index = load_index(evidence_root)
    return done, run_dir, index


@requires_cli
def test_before_after_and_diff_files_show_the_change(tmp_path: Path) -> None:
    done, run_dir, _index = _run_case(tmp_path, "before_and_after")
    assert done.returncode == 0, done.stdout + done.stderr
    case_dir = run_dir / "TC-LIVE-001" / "case"

    before = json.loads((case_dir / "before-db-records-OP-LIST.json").read_text())
    after = json.loads((case_dir / "after-db-records-OP-LIST.json").read_text())
    assert before == [] and len(after) == 1

    records_diff = (case_dir / "diff-db-records-OP-LIST.diff").read_text()
    assert records_diff.startswith("--- before\n+++ after")
    assert '+    "recipient": "someone@example.invalid"' in records_diff
    assert "+INSERT notification 1" in (case_dir / "diff-db-log-OP-READ-DB-LOG.diff").read_text()
    assert "+accepted notification 1" in (case_dir / "diff-app-log-OP-READ-LOGS.diff").read_text()


@requires_cli
def test_app_log_is_judged_on_the_delta_only(tmp_path: Path) -> None:
    # The log already holds an old error. Judged whole, that fails the case...
    done, _run_dir, _index = _run_case(tmp_path / "whole", "after", NOISY_LOG)
    assert done.returncode != 0
    # ...but with before_and_after only the lines this run added count.
    done, _run_dir, _index = _run_case(tmp_path / "delta", "before_and_after", NOISY_LOG)
    assert done.returncode == 0, done.stdout + done.stderr


@requires_cli
def test_a_new_error_in_the_delta_still_fails(tmp_path: Path) -> None:
    plugin_with_error = {
        **PLUGIN,
        "operations": {
            **PLUGIN["operations"],
            # The live service logs an error line for a recipient containing ERROR.
            "OP-SEND": {**PLUGIN["operations"]["OP-SEND"], "body": {"recipient": "ERROR boom"}},
        },
    }
    plugin = tmp_path / "plugin.yaml"
    write_yaml(plugin, plugin_with_error)
    case = make_case(evidence={"sources": SOURCES, "timing": "before_and_after"})
    specs = write_specs(tmp_path, BASELINE, [case], [])
    test_file = generate(tmp_path, specs, plugin, "TC-LIVE-001")
    with live_server() as (url, _state):
        done = run_generated(test_file, {"APP_URL": url, "LIVE_TOKEN": "tok"})
    assert done.returncode != 0


@requires_cli
def test_scenario_collects_before_first_step_and_after_last(tmp_path: Path) -> None:
    plugin = tmp_path / "plugin.yaml"
    write_yaml(plugin, PLUGIN)
    scenario = {
        "id": "SC-LIVE-001",
        "title": "send, then list",
        "preconditions": [],
        "steps": [
            {
                "id": "S-SEND",
                "summary": "send",
                "action": {"operation": "OP-SEND", "params": {"recipient": "a@example.invalid"}},
                "expect": [{"kind": "http_status", "status": 201, "viewpoints": []}],
                "polarity": "nominal",
                "dependsOn": [],
                "produces": {},
                "viewpoints": [],
            },
            {
                "id": "S-LIST",
                "summary": "list",
                "action": {"operation": "OP-LIST", "params": {}},
                "expect": [{"kind": "http_status", "status": 200, "viewpoints": []}],
                "polarity": "nominal",
                "dependsOn": ["S-SEND"],
                "produces": {},
                "viewpoints": [],
            },
        ],
        "cleanup": [],
        # each_step is not implemented in Python: accepted, not a crash.
        "evidence": {"sources": SOURCES, "timing": "each_step"},
        "evidenceWaivers": [],
        "tags": [],
        "viewpoints": [],
    }
    specs = write_specs(tmp_path, BASELINE, [], [scenario])
    test_file = generate(tmp_path, specs, plugin, "SC-LIVE-001")
    evidence_root = tmp_path / "evidence"
    with live_server() as (url, _state):
        done = run_generated(
            test_file,
            {"APP_URL": url, "LIVE_TOKEN": "tok", "ATH_EVIDENCE_DIR": str(evidence_root)},
        )
    assert done.returncode == 0, done.stdout + done.stderr
    run_dir, index = load_index(evidence_root)
    scenario_dir = run_dir / "SC-LIVE-001" / "scenario"
    assert json.loads((scenario_dir / "before-db-records-OP-LIST.json").read_text()) == []
    assert len(json.loads((scenario_dir / "after-db-records-OP-LIST.json").read_text())) == 1
    assert (scenario_dir / "diff-app-log-OP-READ-LOGS.diff").exists()
    assert not index["warnings"]
